### ISSUE TITLE
Packet flying from Japan to San Francisco should fly over Pacific Ocean

### ISSUE THREAD

**Issue by frewsxcv** [unchartedsoftware/torflow#2]

**Comment by kbirk** [comment]
Fixed! Particles will now wrap across the Pacific if it is the shortest route. Thank you for the suggestion!

**Comment by frewsxcv** [comment]
Did this already get deployed? I'm not seeing this at https://torflow.uncharted.software/

![screen shot 2016-01-18 at 10 46 11 pm](https://cloud.githubusercontent.com/assets/416575/12409135/4c98f6c6-be35-11e5-8022-2a2aa72732c5.png)

**Comment by kbirk** [comment]
Should be deployed now.
