### ISSUE TITLE
No fallback content if the user doesn't have WebGL

### ISSUE THREAD

**Issue by strugee** [unchartedsoftware/torflow#6]
At some point, the computer I'm currently on didn't do WebGL (this seems to have changed recently - I'm filing this on the assumption that no one has noticed and this is still an issue). At the time, I noticed that TorFlow didn't have any fallback content for this case, and the only reason I knew WebGL was broken was because I looked at the Web Console. This omission seems unfortunate.

**Comment by kbirk** [comment]
@strugee Thanks for opening this issue. With the recent draft of the WebGL 2.0 spec, it is unfortunate that there are still browsers and devices still do not support WebGL 1.0. For the time being we can add a small dialog panel to present the issue to the user.

**Comment by strugee** [comment]
@kbirk I use Firefox Nightly, so that may have been it... otherwise I have a vague memory of having a known bad video card or something? Not sure. I've hardly ever seen this happen, FWIW :)

**Comment by strugee** [comment]
(As a web developer myself, however, I do agree with you.)
